### ISSUE TITLE
Message signature is not working

### ISSUE THREAD

**Issue by AlvaroVasconcelos** [ConnectyCube/connectycube-flutter-sdk-releases#2] opened 2020-06-07 15:27 UTC
Hello, I saw that Cube Chat Connection.instance.chat Messages Manager is not returning the message flow, I get a log that the message arrived, but the message does not come in my stream.

``` dart
  Stream<CubeMessage> flux;

  void subChat() async {
    if (CubeSessionManager.instance.isActiveSessionValid()) {
      ChatMessagesManager chatMessagesManager =
          await CubeChatConnection.instance.chatMessagesManager;
      flux = chatMessagesManager.chatMessagesStream.asBroadcastStream();
      flux.listen((event) {
        print(event.body);
      });
    }
  }
```

**Comment by TatankaConCube** [comment] 2020-06-10 10:26
hello @AlvaroVasconcelos, please, follow [our documentation](https://developers.connectycube.com/flutter/messaging?id=sendreceive-chat-messages) about sending and receiving messages via Flutter SDK.

**Comment by AlvaroVasconcelos** [comment] 2020-06-10 11:51
@TatankaConCube Yes, but messages do not return in listen!

**Comment by TatankaConCube** [comment] 2020-06-12 12:29
Today I emulated your logic in my test app and didn't get any issues with messages listener. Please provide us full log from flutter console from both sides (sender and receiver), please don't filter it. For publishing logs you can use [Gist](https://gist.github.com/)

**Comment by AlvaroVasconcelos** [comment] 2020-06-12 19:13
It may be easier for you to raise your functional example.

**Comment by TatankaConCube** [comment] 2020-06-18 18:17
Here is nothing to show, I just added parts of code from [documentation](https://developers.connectycube.com/flutter/messaging?id=sendreceive-chat-messages) to our [p2p call sample](https://github.com/ConnectyCube/connectycube-flutter-samples/tree/master/p2p_call_sample), just hardcoded creating dialog and sending message like in your example, added listener and tested)))

**Comment by TatankaConCube** [comment] 2020-07-23 19:14
Looks like the issue is resolved, so closing it.

**Closed by TatankaConCube** 2020-07-23 19:14 UTC
